from __future__ import annotations

from typing import Protocol

from .types import GoalRecord


class NativeGoalBackend(Protocol):
    def inspect(self) -> GoalRecord: ...
    def create(self, objective: str) -> GoalRecord: ...
    def observe(self) -> GoalRecord: ...
    def complete(self, goal_id: str) -> GoalRecord: ...
    def block(self, goal_id: str) -> GoalRecord: ...
